# Linear Regression

In [1]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [121]:
diabetes_X, diabetes_y = datasets.load_diabetes(return_X_y=True)


In [122]:
diabetes_X = np.concatenate((np.ones((diabetes_X.shape[0], 1)), diabetes_X), axis=1)

In [123]:
diabetes_X_train = diabetes_X[:-20]
diabetes_X_test = diabetes_X[-20:]
diabetes_y_train = diabetes_y[:-20]
diabetes_y_test = diabetes_y[-20:]

In [131]:
diabetes_X_train[0]

array([ 1.        ,  0.03807591,  0.05068012,  0.06169621,  0.02187239,
       -0.0442235 , -0.03482076, -0.04340085, -0.00259226,  0.01990749,
       -0.01764613])

In [125]:
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr.fit(diabetes_X_train, diabetes_y_train)

# Make predictions using the testing set
diabetes_y_pred = regr.predict(diabetes_X_test)
print("Coefficients: \n", regr.coef_)
print("Mean squared error: %.2f" % mean_squared_error(diabetes_y_test, diabetes_y_pred))

Coefficients: 
 [ 0.00000000e+00  3.06094248e-01 -2.37635570e+02  5.10538048e+02
  3.27729878e+02 -8.14111926e+02  4.92799595e+02  1.02841240e+02
  1.84603496e+02  7.43509388e+02  7.60966464e+01]
Mean squared error: 2004.52


In [145]:
#theta=np.random.randint(0,100,(diabetes_X_train.shape[1],))
theta = np.ones(diabetes_X_train.shape[1])


In [146]:
theta

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [137]:
j=0
diabetes_y_train[j]-np.dot(theta,diabetes_X_train[j])

149.95045139069572

In [147]:
# batch gradient descent
epoch=1000
rate=0.01
for i in range(epoch):
    sum=np.zeros(diabetes_X_train.shape[1])
    for j in range(diabetes_X_train.shape[0]):
        a = diabetes_y_train[j]-np.dot(theta,diabetes_X_train[j])
        sum+=a*diabetes_X_train[j]
    
    theta = theta + rate * sum /diabetes_X_train.shape[0]
print(theta)

    


   
    

[153.34272606   7.63148401   2.01254871  21.60384754  16.4949544
   8.24493036   6.81061733 -12.70721972  16.11162869  20.89780146
  14.40805516]


In [144]:
#stochastic gradient descent
epoch=5000
rate=0.01
for i in range(epoch):
    for j in range(diabetes_X_train.shape[0]):
        a = diabetes_y_train[j]-np.dot(theta,diabetes_X_train[j])
        theta = theta + rate* a*diabetes_X_train[j]

print(theta)

[ 154.06685833    5.17505119 -235.53252663  510.8695161   327.40611513
 -304.73436671   85.83633305 -122.15088293  123.14356373  553.06229243
   81.08631888]


In [124]:
#矩阵求导
np.dot(np.dot(np.linalg.inv(np.dot(diabetes_X_train.T,diabetes_X_train)),diabetes_X_train.T),diabetes_y_train)

array([ 1.52764292e+02,  3.06094248e-01, -2.37635570e+02,  5.10538048e+02,
        3.27729878e+02, -8.14111926e+02,  4.92799595e+02,  1.02841240e+02,
        1.84603496e+02,  7.43509388e+02,  7.60966464e+01])