In [14]:
import numpy as np

In [15]:
a = np.array([1,2,3,4,5,6])

In [4]:
print(a.shape)
print(a.ndim)
print(a.size)

(6,)
1
6


In [8]:
a=a.reshape(2,3)
# same as list1 = list2, the original ndarry will be changed if new ndarray change
a.shape

(2, 3)

In [3]:
b = np.empty((3,3),np.int64)
c = np.zeros((3,3),np.int8)
d = np.ones((3,3),np.float64)

In [5]:
b,c,d

(array([[                0,                 0,                 0],
        [                0,                 0,              1452],
        [    2701534429184, 18583129488883712,                 0]],
       dtype=int64),
 array([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=int8),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]))

In [7]:
np.arange(1,10,2)
#numpy.arange(start=0, stop, step=1, dtype)

array([1, 3, 5, 7, 9])

In [13]:
np.linspace(1,10,5)
#np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
#endpoint	该值为 true 时，数列中包含stop值，反之不包含，默认是True。
#retstep	如果为 True 时，生成的数组中会显示间距，反之不显示。

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [10]:
np.logspace(1,2,10)
#np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
#base 参数意思是取对数的时候 log 的下标。

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [17]:
a=a.reshape(3,2)

In [19]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a[:,1]

array([2, 4, 6])

In [20]:
a[...,0]

array([1, 3, 5])

In [21]:
a[a>3] #布尔索引

array([4, 5, 6])

In [25]:
a = np.array([[1,1],[1,2]])
b = np.array([[1,0],[0,1]])

In [26]:
a*b

array([[1, 0],
       [0, 2]])

In [27]:
np.dot(a,b)

array([[1, 1],
       [1, 2]])

In [28]:
np.matmul(a,b)

array([[1, 1],
       [1, 2]])

In [29]:
a = a.reshape(4,)
b = b.reshape(4,)

In [31]:
a,b

(array([1, 1, 1, 2]), array([1, 0, 0, 1]))

In [33]:
np.matmul(a,b),np.dot(a,b)

(3, 3)